export const TYPES = [
  { label: 'Улаанбаатар хот', value: 'ulaanbaatar', deliver: 5000 },
  { label: 'Дархан-уул аймаг', value: 'darhan', deliver: 4000 + 5000 },
  { label: 'Архангай аймаг', value: 'arkhangai', deliver: 5000 + 5000 },
  { label: 'Баян-өлгий аймаг', value: 'bayanolgii', deliver: 16500 },
  { label: 'Баянхонгор аймаг', value: 'bayanhongor', deliver: 7000 },
  { label: 'Булган аймаг', value: 'bulgan', deliver: 4000 },
  { label: 'Говь-алтай аймаг', value: 'govialtai', deliver: 11000 },
  { label: 'Дорноговь аймаг', value: 'dornogovi', deliver: 5000 },
  { label: 'Дорнод аймаг', value: 'dornod', deliver: 7000 },
  { label: 'Дундговь аймаг', value: 'dundgovi', deliver: 4000 },
  { label: 'Завхан аймаг', value: 'zawhan', deliver: 10000 },
  { label: 'Өвөрхангай аймаг', value: 'oworhangai', deliver: 5000 },
  { label: 'Өмнөговь аймаг', value: 'omnogovi', deliver: 6000 },
  { label: 'Сүхбаатар аймаг', value: 'suhbaatar', deliver: 6000 },
  { label: 'Сэлэнгэ аймаг', value: 'selenge', deliver: 4000 },
  { label: 'Төв аймаг', value: 'tow', deliver: '' },
  { label: 'Увс аймаг', value: 'uws', deliver: 15400 },
  { label: 'Ховд аймаг', value: 'howd', deliver: 16500 },
  { label: 'Хөвсгөл аймаг', value: 'huwsgul', deliver: 8000 },
  { label: 'Хэнтий аймаг', value: 'hentii', deliver: 4000 },
  { label: 'Орхон аймаг', value: 'orhon', deliver: '' },
  { label: 'Говьсүмбэр аймаг', value: 'govisumber', deliver: 4000 }
];

const ulaanbaatar = [
  { label: 'Баянзүрх дүүрэг', value: 'bayanzurh' },
  { label: 'Баянгол дүүрэг', value: 'bayangol' },
  { label: 'Хан-уул дүүрэг', value: 'hanuul' },
  { label: 'Багануур дүүрэг', value: 'baganuur' },
  { label: 'Сүхбаатар дүүрэг', value: 'suhbaatar' },
  { label: 'Багахангай дүүрэг', value: 'baganhangai' },
  { label: 'Налайх дүүрэг', value: 'nalaih' },
  { label: 'Сонгинохайрхан дүүрэг', value: 'songinohairhan' },
  { label: 'Чингэлтэй дүүрэг', value: 'chingeltei' }
];

const arkhangai = [
  { label: 'Цэцэрлэг сум', value: 'arkhangai' },
  { label: 'Батцэнгэл сум', value: 'arkhangai' },
  { label: 'Булган сум', value: 'arkhangai' },
  { label: 'Жаргалант сум', value: 'arkhangai' },
  { label: 'Ихтамир сум', value: 'arkhangai' },
  { label: 'Өгийнуур сум', value: 'arkhangai' },
  { label: 'Өлзийт сум', value: 'arkhangai' },
  { label: 'Өндөр-Улаан сум', value: 'arkhangai' },
  { label: 'Тариат сум', value: 'arkhangai' },
  { label: 'Төвшрүүлэх сум', value: 'arkhangai' },
  { label: 'Хайрхан сум', value: 'arkhangai' },
  { label: 'Хангай сум', value: 'arkhangai' },
  { label: 'Хашаат сум', value: 'arkhangai' },
  { label: 'Хотонт сум', value: 'arkhangai' },
  { label: 'Цахир сум', value: 'arkhangai' },
  { label: 'Цэнхэр сум', value: 'arkhangai' },
  { label: 'Цэцэрлэг сум', value: 'arkhangai' },
  { label: 'Чулуут сум', value: 'arkhangai' },
  { label: 'Эрдэнэбулган сум', value: 'arkhangai' },
  { label: 'Эрдэнэмандал сум', value: 'arkhangai' }
];

const bayanolgii = [
  { label: 'Өлгий сум', value: 'bayanzurh' },
  { label: 'Алтай сум', value: 'bayanhon' },
  { label: 'Алтанцөгц сум', value: 'bayanhon' },
  { label: 'Баяннуур сум', value: 'bayanhon' },
  { label: 'Бугат сум', value: 'bayanhon' },
  { label: 'Булган сум', value: 'bayanhon' },
  { label: 'Буянт сум', value: 'bayanhon' },
  { label: 'Дэлүүн сум', value: 'bayanhon' },
  { label: 'Ногооннуур сум', value: 'bayanhon' },
  { label: 'Сагсай сум', value: 'bayanhon' },
  { label: 'Толбо сум', value: 'bayanhon' },
  { label: 'Улаанхус сум', value: 'bayanhon' },
  { label: 'Цагааннуур сум', value: 'bayanhon' },
  { label: 'Цэнгэл сум', value: 'bayanhon' }
];

const darhan = [
  { label: 'Дархан сум', value: 'darhan' },
  { label: 'Орхон сум', value: 'darhan' },
  { label: 'Хонгор сум', value: 'darhan' },
  { label: 'Шарын гол сум', value: 'darhan' }
];

const bayanhongor = [
  { label: 'Баянхонгор сум', value: 'bayanhon' },
  { label: 'Баацагаан сум', value: 'bayanhon' },
  { label: 'Баянбулаг сум', value: 'bayanhon' },
  { label: 'Баянговь сум', value: 'bayanhon' },
  { label: 'Баянлиг сум', value: 'bayanhon' },
  { label: 'Баян - Овоо сум', value: 'bayanhon' },
  { label: 'Баян - Өндөр сум', value: 'bayanhon' },
  { label: 'Баянцагаан сум', value: 'bayanhon' },
  { label: 'Богд сум', value: 'bayanhon' },
  { label: 'Бөмбөгөр сум', value: 'bayanhon' },
  { label: 'Бууцагаан сум', value: 'bayanhon' },
  { label: 'Галуут сум', value: 'bayanhon' },
  { label: 'Гурванбулаг сум', value: 'bayanhon' },
  { label: 'Жаргалант сум', value: 'bayanhon' },
  { label: 'Жинст сум', value: 'bayanhon' },
  { label: 'Заг сум', value: 'bayanhon' },
  { label: 'Өлзийт сум', value: 'bayanhon' },
  { label: 'Хүрээмарал сум', value: 'bayanhon' },
  { label: 'Шинэжинст сум', value: 'bayanhon' },
  { label: 'Эрдэнэцогт сум', value: 'bayanhon' }
];

const bulgan = [
  { label: 'Булган сум', value: 'bulgan' },
  { label: 'Баян - Агт сум', value: 'bulgan' },
  { label: 'Баяннуур сум', value: 'bulgan' },
  { label: 'Бугат сум', value: 'bulgan' },
  { label: 'Бүрэгхангай сум', value: 'bulgan' },
  { label: 'Гурванбулаг сум', value: 'bulgan' },
  { label: 'Дашинчилэн сум', value: 'bulgan' },
  { label: 'Могод сум', value: 'bulgan' },
  { label: 'Орхон сум', value: 'bulgan' },
  { label: 'Рашаант сум', value: 'bulgan' },
  { label: 'Сайхан сум', value: 'bulgan' },
  { label: 'Сэлэнгэ сум', value: 'bulgan' },
  { label: 'Тэшиг сум', value: 'bulgan' },
  { label: 'Хангал сум', value: 'bulgan' },
  { label: 'Хишиг - Өндөр сум', value: 'bulgan' },
  { label: 'Хутаг - Өндөр сум', value: 'bulgan' }
];

const govialtai = [
  { label: 'Алтай сум', value: 'govialtai' },
  { label: 'Баян - Уул сум', value: 'govialtai' },
  { label: 'Бигэр сум', value: 'govialtai' },
  { label: 'Бугат сум', value: 'govialtai' },
  { label: 'Дарви сум', value: 'govialtai' },
  { label: 'Дэлгэр сум', value: 'govialtai' },
  { label: 'Жаргалан сум', value: 'govialtai' },
  { label: 'Есөнбулаг сум', value: 'govialtai' },
  { label: 'Тайшир сум', value: 'govialtai' },
  { label: 'Тонхил сум', value: 'govialtai' },
  { label: 'Төгрөг сум', value: 'govialtai' },
  { label: 'Халиун сум', value: 'govialtai' },
  { label: 'Хөхморьт сум', value: 'govialtai' },
  { label: 'Цогт сум', value: 'govialtai' },
  { label: 'Цээл сум', value: 'govialtai' },
  { label: 'Чандмань сум', value: 'govialtai' },
  { label: 'Шарга сум', value: 'govialtai' },
  { label: 'Говьялтай сум', value: 'govialtai' },
  { label: 'Эрдэнэ сум', value: 'govialtai' }
];

const dornogovi = [
  { label: 'Сайншанд сум', value: 'dornogovi' },
  { label: 'Айраг сум', value: 'dornogovi' },
  { label: 'Алтанширээ сум', value: 'dornogovi' },
  { label: 'Даланжаргалан сум', value: 'dornogovi' },
  { label: 'Замын - Үүд сум', value: 'dornogovi' },
  { label: 'Иххэт сум', value: 'dornogovi' },
  { label: 'Мандах сум', value: 'dornogovi' },
  { label: 'Өргөн сум', value: 'dornogovi' },
  { label: 'Сайхандулаан сум', value: 'dornogovi' },
  { label: 'Улаанбадрах сум', value: 'dornogovi' },
  { label: 'Хатанбулаг сум', value: 'dornogovi' },
  { label: 'Хөвсгөл сум', value: 'dornogovi' },
  { label: 'Эрдэнэ сум', value: 'dornogovi' }
];

const dornod = [
  { label: 'Чойбалсан сум', value: 'dornod' },
  { label: 'Баяндун сум', value: 'dornod' },
  { label: 'Баян - Уул сум', value: 'dornod' },
  { label: 'Булган сум', value: 'dornod' },
  { label: 'Гурванзагал сум', value: 'dornod' },
  { label: 'Дашбалбар сум', value: 'dornod' },
  { label: 'Матад сум', value: 'dornod' },
  { label: 'Сэргэлэн сум', value: 'dornod' },
  { label: 'Халхгол сум', value: 'dornod' },
  { label: 'Хөлөнбуйр сум', value: 'dornod' },
  { label: 'Хэрлэн сум', value: 'dornod' },
  { label: 'Цагаан - Овоо сум', value: 'dornod' },
  { label: 'Чойбалсан сум', value: 'dornod' },
  { label: 'Чулуунхороот сум', value: 'dornod' }
];

const dundgovi = [
  { label: 'Мандалговь сум', value: 'dundgovi' },
  { label: 'Адаацаг сум', value: 'dundgovi' },
  { label: 'Баянжаргалан сум', value: 'dundgovi' },
  { label: 'Говь - Угтаал сум', value: 'dundgovi' },
  { label: 'Гурвансайхан сум', value: 'dundgovi' },
  { label: 'Дэлгэрхангай сум', value: 'dundgovi' },
  { label: 'Дэлгэрцогт сум', value: 'dundgovi' },
  { label: 'Дэрэн сум', value: 'dundgovi' },
  { label: 'Луус сум', value: 'dundgovi' },
  { label: 'Өлзийт сум', value: 'dundgovi' },
  { label: 'Өндөршил сум', value: 'dundgovi' },
  { label: 'Сайнцагаан сум', value: 'dundgovi' },
  { label: 'Сайхан - Овоо сум', value: 'dundgovi' },
  { label: 'Хулд сум', value: 'dundgovi' },
  { label: 'Цагаандэлгэр сум', value: 'dundgovi' },
  { label: 'Эрдэнэдалай сум', value: 'dundgovi' }
];

const zawhan = [
  { label: 'Улиастай сум', value: 'zawhan' },
  { label: 'Алдархаан сум', value: 'zawhan' },
  { label: 'Асгат сум', value: 'zawhan' },
  { label: 'Баянтэс сум', value: 'zawhan' },
  { label: 'Баянхайрхан сум', value: 'zawhan' },
  { label: 'Дөрвөлжин сум', value: 'zawhan' },
  { label: 'Завханмандал сум', value: 'zawhan' },
  { label: 'Идэр сум', value: 'zawhan' },
  { label: 'Их - Уул сум', value: 'zawhan' },
  { label: 'Нөмрөг сум', value: 'zawhan' },
  { label: 'Отгон сум', value: 'zawhan' },
  { label: 'Сонгино сум', value: 'zawhan' },
  { label: 'Тосонцэнгэл сум', value: 'zawhan' },
  { label: 'Түдэвтэй сум', value: 'zawhan' },
  { label: 'Тэлмэн сум', value: 'zawhan' },
  { label: 'Тэс сум', value: 'zawhan' },
  { label: 'Ургамал сум', value: 'zawhan' },
  { label: 'Цагаанхайрхан сум', value: 'zawhan' },
  { label: 'Цагаанчулуут сум', value: 'zawhan' },
  { label: 'Цэцэн - Уул сум', value: 'zawhan' },
  { label: 'Шилүүстэй сум', value: 'zawhan' },
  { label: 'Эрдэнэхайрхан сум', value: 'zawhan' },
  { label: 'Яруу сум', value: 'zawhan' }
];

const orhon = [
  { label: 'Эрдэнэт сум', value: 'orhon' },
  { label: 'Баян - Өндөр сум', value: 'orhon' },
  { label: 'Жаргалант сум', value: 'orhon' }
];

const oworhangai = [
  { label: 'Арвайхээр сум', value: 'oworhangai' },
  { label: 'Баруунбаян - Улаан сум', value: 'oworhangai' },
  { label: 'Бат - Өлзий сум', value: 'oworhangai' },
  { label: 'Баянгол сум', value: 'oworhangai' },
  { label: 'Баян - Өндөр сум', value: 'oworhangai' },
  { label: 'Богд сум', value: 'oworhangai' },
  { label: 'Бүрд сум', value: 'oworhangai' },
  { label: 'Гучин - Ус сум', value: 'oworhangai' },
  { label: 'Есөнзүйл сум', value: 'oworhangai' },
  { label: 'Зүүнбаян - Улаан сум', value: 'oworhangai' },
  { label: 'Нарийнтээл сум', value: 'oworhangai' },
  { label: 'Өлзийт сум', value: 'oworhangai' },
  { label: 'Сант сум', value: 'oworhangai' },
  { label: 'Тарагт сум', value: 'oworhangai' },
  { label: 'Төгрөг сум', value: 'oworhangai' },
  { label: 'Уянга сум', value: 'oworhangai' },
  { label: 'Хайрхандулаан сум', value: 'oworhangai' },
  { label: 'Хархорин сум', value: 'oworhangai' },
  { label: 'Хужирт сум', value: 'oworhangai' }
];

const omnogovi = [
  { label: 'Даланзадгад сум', value: 'omnogovi' },
  { label: 'Баяндалай сум', value: 'omnogovi' },
  { label: 'Баян - Овоо сум', value: 'omnogovi' },
  { label: 'Булган сум', value: 'omnogovi' },
  { label: 'Гурвантэс сум', value: 'omnogovi' },
  { label: 'Мандал - Овоо сум', value: 'omnogovi' },
  { label: 'Манлай сум', value: 'omnogovi' },
  { label: 'Ноён сум', value: 'omnogovi' },
  { label: 'Номгон сум', value: 'omnogovi' },
  { label: 'Сэврэй сум', value: 'omnogovi' },
  { label: 'Ханбогд сум', value: 'omnogovi' },
  { label: 'Ханхонгор сум', value: 'omnogovi' },
  { label: 'Хүрмэн сум', value: 'omnogovi' },
  { label: 'Цогт - Овоо сум', value: 'omnogovi' },
  { label: 'Цогтцэций сум', value: 'omnogovi' }
];

const sukhbaatar = [
  { label: 'Баруун-Урт сум', value: 'sukhbaatar' },
  { label: 'Асгат сум', value: 'sukhbaatar' },
  { label: 'Баяндэлгэр сум', value: 'sukhbaatar' },
  { label: 'Дарьганга сум', value: 'sukhbaatar' },
  { label: 'Мөнххаан сум', value: 'sukhbaatar' },
  { label: 'Наран сум', value: 'sukhbaatar' },
  { label: 'Онгон сум', value: 'sukhbaatar' },
  { label: 'Сүхбаатар сум', value: 'sukhbaatar' },
  { label: 'Түвшинширээ сум', value: 'sukhbaatar' },
  { label: 'Түмэнцогт сум', value: 'sukhbaatar' },
  { label: 'Уулбаян сум', value: 'sukhbaatar' },
  { label: 'Халзан сум', value: 'sukhbaatar' },
  { label: 'Эрдэнэцагаан сум', value: 'sukhbaatar' }
];

const selenge = [
  { label: 'Сүхбаатар сум', value: 'sukhbaatar' },
  { label: 'Алтанбулаг сум', value: 'sukhbaatar' },
  { label: 'Баруунбүрэн сум', value: 'sukhbaatar' },
  { label: 'Баянгол сум', value: 'sukhbaatar' },
  { label: 'Ерөө сум', value: 'sukhbaatar' },
  { label: 'Жавхлант сум', value: 'sukhbaatar' },
  { label: 'Зүүнбүрэн сум', value: 'sukhbaatar' },
  { label: 'Мандал сум', value: 'sukhbaatar' },
  { label: 'Орхон сум', value: 'sukhbaatar' },
  { label: 'Орхонтуул сум', value: 'sukhbaatar' },
  { label: 'Сайхан сум', value: 'sukhbaatar' },
  { label: 'Сант сум', value: 'sukhbaatar' },
  { label: 'Түшиг сум', value: 'sukhbaatar' },
  { label: 'Хушаат сум', value: 'sukhbaatar' },
  { label: 'Хүдэр сум', value: 'sukhbaatar' },
  { label: 'Цагааннуур сум', value: 'sukhbaatar' },
  { label: 'Шаамар сум', value: 'sukhbaatar' }
];

const tow = [
  { label: 'Зуунмод сум', value: 'sukhbaatar' },
  { label: 'Алтанбулаг сум', value: 'sukhbaatar' },
  { label: 'Аргалант сум', value: 'sukhbaatar' },
  { label: 'Архуст сум', value: 'sukhbaatar' },
  { label: 'Батсүмбэр сум', value: 'sukhbaatar' },
  { label: 'Баян сум', value: 'sukhbaatar' },
  { label: 'Баяндэлгэр сум', value: 'sukhbaatar' },
  { label: 'Баянжаргалан сум', value: 'sukhbaatar' },
  { label: 'Баян - Өнжүүл сум', value: 'sukhbaatar' },
  { label: 'Баянхангай сум', value: 'sukhbaatar' },
  { label: 'Баянцагаан сум', value: 'sukhbaatar' },
  { label: 'Баянцогт сум', value: 'sukhbaatar' },
  { label: 'Баянчандмань сум', value: 'sukhbaatar' },
  { label: 'Борнуур сум', value: 'sukhbaatar' },
  { label: 'Бүрэн сум', value: 'sukhbaatar' },
  { label: 'Дэлгэрхаан сум', value: 'sukhbaatar' },
  { label: 'Жаргалант сум', value: 'sukhbaatar' },
  { label: 'Заамар сум', value: 'sukhbaatar' },
  { label: 'Лүн сум', value: 'sukhbaatar' },
  { label: 'Мөнгөнморьт сум', value: 'sukhbaatar' },
  { label: 'Өндөрширээт сум', value: 'sukhbaatar' },
  { label: 'Сүмбэр сум', value: 'sukhbaatar' },
  { label: 'Сэргэлэн сум', value: 'sukhbaatar' },
  { label: 'Угтаалцайдам сум', value: 'sukhbaatar' },
  { label: 'Цээл сум', value: 'sukhbaatar' },
  { label: 'Эрдэнэ сум', value: 'sukhbaatar' },
  { label: 'Эрдэнэсант сум', value: 'sukhbaatar' }
];

const uws = [
  { label: 'Улаангом сум', value: 'sukhbaatar' },
  { label: 'Баруунтуруун сум', value: 'sukhbaatar' },
  { label: 'Бөхмөрөн сум', value: 'sukhbaatar' },
  { label: 'Баяндэлгэр сум', value: 'sukhbaatar' },
  { label: 'Давст сум', value: 'sukhbaatar' },
  { label: 'Завхан сум', value: 'sukhbaatar' },
  { label: 'Зүүнговь сум', value: 'sukhbaatar' },
  { label: 'Зүүнхангай сум', value: 'sukhbaatar' },
  { label: 'Малчин сум', value: 'sukhbaatar' },
  { label: 'Наранбулаг сум', value: 'sukhbaatar' },
  { label: 'Өлгий сум', value: 'sukhbaatar' },
  { label: 'Өмнөговь сум', value: 'sukhbaatar' },
  { label: 'Өндөрхангай сум', value: 'sukhbaatar' },
  { label: 'Сагил сум', value: 'sukhbaatar' },
  { label: 'Тариалан сум', value: 'sukhbaatar' },
  { label: 'Түргэн сум', value: 'sukhbaatar' },
  { label: 'Тэс сум', value: 'sukhbaatar' },
  { label: 'Ховд сум', value: 'sukhbaatar' },
  { label: 'Хяргас сум', value: 'sukhbaatar' },
  { label: 'Цагаанхайрхан сум', value: 'sukhbaatar' }
];

const howd = [
  { label: 'Ховд сум', value: 'sukhbaatar' },
  { label: 'Алтай сум', value: 'sukhbaatar' },
  { label: 'Булган сум', value: 'sukhbaatar' },
  { label: 'Буянт сум', value: 'sukhbaatar' },
  { label: 'Дарви сум', value: 'sukhbaatar' },
  { label: 'Дөргөн сум', value: 'sukhbaatar' },
  { label: 'Дуут сум', value: 'sukhbaatar' },
  { label: 'Жаргалант сум', value: 'sukhbaatar' },
  { label: 'Зэрэг сум', value: 'sukhbaatar' },
  { label: 'Манхан сум', value: 'sukhbaatar' },
  { label: 'Мөнххайрхан сум', value: 'sukhbaatar' },
  { label: 'Мөст сум', value: 'sukhbaatar' },
  { label: 'Мянгад сум', value: 'sukhbaatar' },
  { label: 'Үенч сум', value: 'sukhbaatar' },
  { label: 'Ховд сум', value: 'sukhbaatar' },
  { label: 'Цэцэг сум', value: 'sukhbaatar' },
  { label: 'Чандмань сум', value: 'sukhbaatar' },
  { label: 'Эрдэнэбүрэн сум', value: 'sukhbaatar' }
];

const huwsgul = [
  { label: 'Мөрөн сум', value: 'sukhbaatar' },
  { label: 'Алаг - Эрдэнэ сум', value: 'sukhbaatar' },
  { label: 'Арбулаг сум', value: 'sukhbaatar' },
  { label: 'Баянзүрх сум', value: 'sukhbaatar' },
  { label: 'Бүрэнтогтох сум', value: 'sukhbaatar' },
  { label: 'Галт сум', value: 'sukhbaatar' },
  { label: 'Жаргалант сум', value: 'sukhbaatar' },
  { label: 'Их - Уул сум', value: 'sukhbaatar' },
  { label: 'Мөрөн сум', value: 'sukhbaatar' },
  { label: 'Рашаант сум', value: 'sukhbaatar' },
  { label: 'Рэнчинлхүмбэ сум', value: 'sukhbaatar' },
  { label: 'Тариалан сум', value: 'sukhbaatar' },
  { label: 'Тосонцэнгэл сум', value: 'sukhbaatar' },
  { label: 'Төмөрбулаг сум', value: 'sukhbaatar' },
  { label: 'Түнэл сум', value: 'sukhbaatar' },
  { label: 'Улаан - Уул сум', value: 'sukhbaatar' },
  { label: 'Ханх сум', value: 'sukhbaatar' },
  { label: 'Хатгал сум', value: 'sukhbaatar' },
  { label: 'Цагааннуур сум', value: 'sukhbaatar' },
  { label: 'Цагаан - Уул сум', value: 'sukhbaatar' },
  { label: 'Цагаан - Үүр сум', value: 'sukhbaatar' },
  { label: 'Цэцэрлэг сум', value: 'sukhbaatar' },
  { label: 'Чандмань - Өндөр сум', value: 'sukhbaatar' },
  { label: 'Шинэ - Идэр сум', value: 'sukhbaatar' },
  { label: 'Эрдэнэбулган сум', value: 'sukhbaatar' }
];
const hentii = [
  { label: 'Чингис сум', value: 'sukhbaatar' },
  { label: 'Батноров сум', value: 'sukhbaatar' },
  { label: 'Батширээт сум', value: 'sukhbaatar' },
  { label: 'Баян - Адарга сум', value: 'sukhbaatar' },
  { label: 'Баянмөнх сум', value: 'sukhbaatar' },
  { label: 'Баян - Овоо сум', value: 'sukhbaatar' },
  { label: 'Баянхутаг сум', value: 'sukhbaatar' },
  { label: 'Биндэр сум', value: 'sukhbaatar' },
  { label: 'Бор - Өндөр сум', value: 'sukhbaatar' },
  { label: 'Галшар сум', value: 'sukhbaatar' },
  { label: 'Дадал сум', value: 'sukhbaatar' },
  { label: 'Дархан сум', value: 'sukhbaatar' },
  { label: 'Дэлгэрхаан сум', value: 'sukhbaatar' },
  { label: 'Жаргалтхаан сум', value: 'sukhbaatar' },
  { label: 'Мөрөн сум', value: 'sukhbaatar' },
  { label: 'Норовлин сум', value: 'sukhbaatar' },
  { label: 'Өмнөдэлгэр сум', value: 'sukhbaatar' },
  { label: 'Хэрлэн сум', value: 'sukhbaatar' },
  { label: 'Цэнхэрмандал сум', value: 'sukhbaatar' }
];

// Duureg sumuudiin horoo, bag

const baganuur = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' }
];
const baganhangai = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' }
];
const bayangol = [
  { label: '1-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '2-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '3-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '4-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '5-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '6-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '7-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '8-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '9-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '10-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '11-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '12-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '13-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '14-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '15-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '16-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '17-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '18-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '19-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '20-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '21-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '22-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '23-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '24-р хороо', value: 'khoroo', deliver: 5000 },
  { label: '25-р хороо', value: 'khoroo', deliver: 5000 }
];

const bayanzurkh = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' },
  { label: '8-р хороо', value: 'khoroo' },
  { label: '9-р хороо', value: 'khoroo' },
  { label: '10-р хороо', value: 'khoroo' },
  { label: '11-р хороо', value: 'khoroo' },
  { label: '12-р хороо', value: 'khoroo' },
  { label: '13-р хороо', value: 'khoroo' },
  { label: '14-р хороо', value: 'khoroo' },
  { label: '15-р хороо', value: 'khoroo' },
  { label: '16-р хороо', value: 'khoroo' },
  { label: '17-р хороо', value: 'khoroo' },
  { label: '18-р хороо', value: 'khoroo' },
  { label: '19-р хороо', value: 'khoroo' },
  { label: '20-р хороо', value: 'khoroo' },
  { label: '21-р хороо', value: 'khoroo' },
  { label: '22-р хороо', value: 'khoroo' },
  { label: '23-р хороо', value: 'khoroo' },
  { label: '24-р хороо', value: 'khoroo' },
  { label: '25-р хороо', value: 'khoroo' },
  { label: '26-р хороо', value: 'khoroo' },
  { label: '27-р хороо', value: 'khoroo' },
  { label: '28-р хороо', value: 'khoroo' }
];

const nalaih = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' }
];

const songinohairhan = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' },
  { label: '8-р хороо', value: 'khoroo' },
  { label: '9-р хороо', value: 'khoroo' },
  { label: '10-р хороо', value: 'khoroo' },
  { label: '11-р хороо', value: 'khoroo' },
  { label: '12-р хороо', value: 'khoroo' },
  { label: '13-р хороо', value: 'khoroo' },
  { label: '14-р хороо', value: 'khoroo' },
  { label: '15-р хороо', value: 'khoroo' },
  { label: '16-р хороо', value: 'khoroo' },
  { label: '17-р хороо', value: 'khoroo' },
  { label: '18-р хороо', value: 'khoroo' },
  { label: '19-р хороо', value: 'khoroo' },
  { label: '20-р хороо', value: 'khoroo' },
  { label: '21-р хороо', value: 'khoroo' },
  { label: '22-р хороо', value: 'khoroo' },
  { label: '23-р хороо', value: 'khoroo' },
  { label: '24-р хороо', value: 'khoroo' },
  { label: '25-р хороо', value: 'khoroo' },
  { label: '26-р хороо', value: 'khoroo' },
  { label: '27-р хороо', value: 'khoroo' },
  { label: '28-р хороо', value: 'khoroo' },
  { label: '29-р хороо', value: 'khoroo' },
  { label: '30-р хороо', value: 'khoroo' },
  { label: '31-р хороо', value: 'khoroo' },
  { label: '32-р хороо', value: 'khoroo' },
  { label: '33-р хороо', value: 'khoroo' },
  { label: '34-р хороо', value: 'khoroo' },
  { label: '35-р хороо', value: 'khoroo' },
  { label: '36-р хороо', value: 'khoroo' },
  { label: '37-р хороо', value: 'khoroo' },
  { label: '38-р хороо', value: 'khoroo' },
  { label: '39-р хороо', value: 'khoroo' },
  { label: '40-р хороо', value: 'khoroo' },
  { label: '41-р хороо', value: 'khoroo' },
  { label: '42-р хороо', value: 'khoroo' },
  { label: '43-р хороо', value: 'khoroo' }
];

const suhbaatar = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' },
  { label: '8-р хороо', value: 'khoroo' },
  { label: '9-р хороо', value: 'khoroo' },
  { label: '10-р хороо', value: 'khoroo' },
  { label: '11-р хороо', value: 'khoroo' },
  { label: '12-р хороо', value: 'khoroo' },
  { label: '13-р хороо', value: 'khoroo' },
  { label: '14-р хороо', value: 'khoroo' },
  { label: '15-р хороо', value: 'khoroo' },
  { label: '16-р хороо', value: 'khoroo' },
  { label: '17-р хороо', value: 'khoroo' },
  { label: '18-р хороо', value: 'khoroo' },
  { label: '19-р хороо', value: 'khoroo' },
  { label: '20-р хороо', value: 'khoroo' }
];

const hanuul = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' },
  { label: '8-р хороо', value: 'khoroo' },
  { label: '9-р хороо', value: 'khoroo' },
  { label: '10-р хороо', value: 'khoroo' },
  { label: '11-р хороо', value: 'khoroo' },
  { label: '12-р хороо', value: 'khoroo' },
  { label: '13-р хороо', value: 'khoroo' },
  { label: '14-р хороо', value: 'khoroo' },
  { label: '15-р хороо', value: 'khoroo' },
  { label: '16-р хороо', value: 'khoroo' },
  { label: '17-р хороо', value: 'khoroo' },
  { label: '18-р хороо', value: 'khoroo' },
  { label: '19-р хороо', value: 'khoroo' },
  { label: '20-р хороо', value: 'khoroo' },
  { label: '21-р хороо', value: 'khoroo' }
];

const chingeltei = [
  { label: '1-р хороо', value: 'khoroo' },
  { label: '2-р хороо', value: 'khoroo' },
  { label: '3-р хороо', value: 'khoroo' },
  { label: '4-р хороо', value: 'khoroo' },
  { label: '5-р хороо', value: 'khoroo' },
  { label: '6-р хороо', value: 'khoroo' },
  { label: '7-р хороо', value: 'khoroo' },
  { label: '8-р хороо', value: 'khoroo' },
  { label: '9-р хороо', value: 'khoroo' },
  { label: '10-р хороо', value: 'khoroo' },
  { label: '11-р хороо', value: 'khoroo' },
  { label: '12-р хороо', value: 'khoroo' },
  { label: '13-р хороо', value: 'khoroo' },
  { label: '14-р хороо', value: 'khoroo' },
  { label: '15-р хороо', value: 'khoroo' },
  { label: '16-р хороо', value: 'khoroo' },
  { label: '17-р хороо', value: 'khoroo' },
  { label: '18-р хороо', value: 'khoroo' },
  { label: '19-р хороо', value: 'khoroo' }
];

export const Duureg = {
  ulaanbaatar,
  dornod,
  dundgovi,
  zawhan,
  dornogovi,
  govialtai,
  darhan,
  arkhangai,
  bayanhongor,
  bulgan,
  bayanolgii,
  orhon,
  howd,
  huwsgul,
  hentii,
  uws,
  tow,
  sukhbaatar,
  selenge,
  omnogovi,
  oworhangai,
  baganuur,
  baganhangai,
  bayangol,
  bayanzurkh,
  nalaih,
  songinohairhan,
  suhbaatar,
  hanuul,
  chingeltei
};
